# Generated by Django 3.0.4 on 2020-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200330_1827'),
        ('cartshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartshop',
            name='products',
            field=models.ManyToManyField(through='cartshop.CartProducts', to='products.Product'),
        ),
    ]
